from django.urls import path
from . import views
 
urlpatterns = [
    path('', views.home, name='home'),
    path('patients/', views.patient_list, name='patient_list'),
    path('patients/create', views.patient_create, name='patient_create' ),
    path('patients/<int:patient_id>/edit/', views.patient_edit, name='patient_edit'),
    path('patients/<int:patient_id>/delete/', views.patient_delete, name='patient_delete'),
    path('addresses/', views.address_list, name='address_list'),
    path('addresses/create/', views.address_create, name='address_create'),
    path('addresses/<int:address_id>/edit/', views.address_edit, name='address_edit'),
    path('addresses/<int:address_id>/delete/', views.address_delete, name='address_delete'),
    path('emergencycontacts/', views.emergencycontact_list, name='emergencycontact_list'),
    path('emergencycontacts/create/', views.emergencycontact_create, name='emergencycontact_create'),
    path('emergencycontacts/<int:contact_id>/edit/', views.emergencycontact_edit, name='emergencycontact_edit'),
    path('emergencycontacts/<int:contact_id>/delete/', views.emergencycontact_delete, name='emergencycontact_delete'),
    path('guardians/', views.guardian_list, name='guardian_list'),
    path('guardians/create/', views.guardian_create, name='guardian_create'),
    path('guardians/<int:guardian_id>/edit/', views.guardian_edit, name='guardian_edit'),
    path('guardians/<int:guardian_id>/delete/', views.guardian_delete, name='guardian_delete'),
    path('admissions/', views.admission_list, name='admission_list'),
    path('admissions/create/', views.admission_create, name='admission_create'),
    path('admissions/<int:admission_id>/edit/', views.admission_edit, name='admission_edit'),
    path('admissions/<int:admission_id>/delete/', views.admission_delete, name='admission_delete'),
    path('allergies/', views.allergy_list, name='allergy_list'),
    path('allergies/create/', views.allergy_create, name='allergy_create'),
    path('allergies/<int:allergy_id>/edit/', views.allergy_edit, name='allergy_edit'),
    path('allergies/<int:allergy_id>/delete/', views.allergy_delete, name='allergy_delete'),
    path('discharges/', views.discharge_list,   name='discharge_list'),
    path('discharges/create/', views.discharge_create, name='discharge_create'),
    path('discharges/<int:discharge_id>/edit/', views.discharge_edit,   name='discharge_edit'),
    path('discharges/<int:discharge_id>/delete/', views.discharge_delete, name='discharge_delete'),
    path('patientnotes/', views.patientnote_list,   name='patientnote_list'),
    path('patientnotes/create/', views.patientnote_create, name='patientnote_create'),
    path('patientnotes/<int:note_id>/edit/', views.patientnote_edit,   name='patientnote_edit'),
    path('patientnotes/<int:note_id>/delete/', views.patientnote_delete, name='patientnote_delete'),
    path('medicalhistory/', views.medicalhistory_list,   name='medicalhistory_list'),
    path('medicalhistory/create/', views.medicalhistory_create, name='medicalhistory_create'),
    path('medicalhistory/<int:history_id>/edit/', views.medicalhistory_edit,   name='medicalhistory_edit'),
    path('medicalhistory/<int:history_id>/delete/', views.medicalhistory_delete, name='medicalhistory_delete'),
    path('insuranceinfo/', views.insuranceinfo_list,   name='insuranceinfo_list'),
    path('insuranceinfo/create/', views.insuranceinfo_create, name='insuranceinfo_create'),
    path('insuranceinfo/<int:insurance_id>/edit/', views.insuranceinfo_edit,   name='insuranceinfo_edit'),
    path('insuranceinfo/<int:insurance_id>/delete/', views.insuranceinfo_delete, name='insuranceinfo_delete'),
]